# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

# Windows-specific configurations
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

# These flags help with the linking process on Windows
rustflags = [
  "-Zshare-generics=off",
  "-Clink-arg=/NODEFAULTLIB:libcmt",
  "-Clink-arg=/NODEFAULTLIB:libcmtd",
  "-Clink-arg=/NODEFAULTLIB:msvcrtd",
  "-Clink-arg=/NODEFAULTLIB:msvcprtd",
]
